Update keymaker-create-account-for-iam-user

diff --git a/scripts/keymaker-create-account-for-iam-user b/scripts/keymaker-create-account-for-iam-user
--- a/scripts/keymaker-create-account-for-iam-user
+++ b/scripts/keymaker-create-account-for-iam-user
@@ -14,7 +14,7 @@ else
     NEW_UID=$(keymaker get_uid "$PAM_USER")
     /usr/sbin/adduser "$PAM_USER" --comment "$PAM_USER" --uid "$NEW_UID"
     for group in $(keymaker get_groups "$PAM_USER"); do
-        usermod --append --groups "$group" "$PAM_USER" || echo "$0: Error while adding user to group"
+        /usr/sbin/usermod --append --groups "$group" "$PAM_USER" || echo "$0: Error while adding user to group"
     done
     echo "Keymaker: Your user account has been replicated onto this host, but SSH will not recognize it until you reconnect."
     echo "Keymaker: Connect again to log in to your account."
